Resources:
   myInstance:
     Type: 'AWS::EC2::Instance'
     Properties: 
        ImageId: ami-0912f71e06545ad88
        InstanceType: t2.micro
        KeyName: Gravitee
        SecurityGroupIds:
          - sg-08ec084b990e1d09f
        UserData:
          Fn::Base64: !Sub |
             #!/bin/bash
             yum update -y
             service httpd start
             chkconfig httpd on